sudo: false
language: python

# tell travis to cache ~/.cache/pip
cache: pip

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOX_ENV=packaging

  - python: 3.6
    env: TOX_ENV=pep8

  - python: 2.7
    env: TOX_ENV=py27

  - python: 3.5
    env: TOX_ENV=py36

  - python: 3.6
    env: TOX_ENV=py36

  - python: 3.7
    env: TOX_ENV=py37

  - python: 3.6
    env: TOX_ENV=check_isort

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
